FROM wordpress

# copy app
ADD ./ /var/www/html

# https://hub.docker.com/_/wordpress/
# WORDPRESS_DB_HOST: db
# WORDPRESS_DB_USER: exampleuser
# WORDPRESS_DB_PASSWORD: examplepass
# WORDPRESS_DB_NAME: exampledb

# entrypoint may be unecessary as there is no binary to run
# ENTRYPOINT ["./slam2"]

EXPOSE 8080
